export const queryKeys = {
  health: ["health"] as const,
  services: ["services"] as const,
  service: (serviceName: string) => ["services", serviceName] as const,
  serviceStatus: (serviceName: string) => ["services", serviceName, "status"] as const,
  serviceResources: (serviceName: string) => ["services", serviceName, "resources"] as const,
  serviceResourceTemplates: (serviceName: string) => ["services", serviceName, "resource-templates"] as const,
  servicePrompts: (serviceName: string) => ["services", serviceName, "prompts"] as const,
  toolsRoot: ["tools"] as const,
  tools: (serviceName?: string) => ["tools", serviceName ?? "all"] as const,
  agents: ["agents"] as const,
  agent: (agentId: string) => ["agents", agentId] as const,
  agentServices: (agentId: string) => ["agents", agentId, "services"] as const,
  agentToolsRoot: (agentId: string) => ["agents", agentId, "tools"] as const,
  agentTools: (agentId: string, serviceName?: string) => ["agents", agentId, "tools", serviceName ?? "all"] as const,
  config: ["config"] as const,
  agentConfig: (agentId: string) => ["agents", agentId, "config"] as const,
  cacheHealth: ["cache", "health"] as const,
  cacheInspect: ["cache", "inspect"] as const,
  meta: ["meta"] as const,
  settings: ["settings"] as const,
}
