export const queryKeys = {
  health: ["health"] as const,
  instances: ["instances"] as const,
  instance: (instanceId: string) => ["instances", instanceId] as const,
  instanceStatus: (instanceId: string) => ["instances", instanceId, "status"] as const,
  instanceAuth: (instanceId: string) => ["instances", instanceId, "auth"] as const,
  instanceTools: (instanceId: string) => ["instances", instanceId, "tools"] as const,
  instanceResources: (instanceId: string) => ["instances", instanceId, "resources"] as const,
  instanceResourceTemplates: (instanceId: string) => ["instances", instanceId, "resource-templates"] as const,
  instancePrompts: (instanceId: string) => ["instances", instanceId, "prompts"] as const,
  agents: ["agents"] as const,
  agent: (agentId: string) => ["agents", agentId] as const,
  agentServices: (agentId: string) => ["agents", agentId, "instances"] as const,
  config: ["config", "store"] as const,
  agentConfig: (agentId: string) => ["config", "agent", agentId] as const,
  cacheHealth: ["cache", "health"] as const,
  cacheInspect: ["cache", "inspect"] as const,
  meta: ["meta"] as const,
  settings: ["settings"] as const,
}
