import { readFileSync, readdirSync, writeFileSync, mkdirSync } from "node:fs"
import { dirname, join } from "node:path"
import { fileURLToPath } from "node:url"

const __filename = fileURLToPath(import.meta.url)
const __dirname = dirname(__filename)

const repoRoot = join(__dirname, "../..")
const i18nDir = join(repoRoot, "i18n")
const outDir = join(__dirname, "../src/generated")
const outFile = join(outDir, "i18n-dictionaries.ts")

function parseFlatYaml(content) {
  const entries = {}
  for (const raw of content.split("\n")) {
    const line = raw.trim()
    if (!line || line.startsWith("#")) continue
    const idx = line.indexOf(":")
    if (idx === -1) continue
    const key = line.slice(0, idx).trim()
    let value = line.slice(idx + 1).trim()
    value = value.replace(/^["']|["']$/g, "")
    entries[key] = value
  }
  return entries
}

const files = readdirSync(i18nDir)
  .filter((name) => name.endsWith(".yaml"))
  .sort()

const dictionaries = {}
for (const file of files) {
  const locale = file.replace(/\.yaml$/, "")
  const content = readFileSync(join(i18nDir, file), "utf8")
  dictionaries[locale] = parseFlatYaml(content)
}

const entries = Object.entries(dictionaries)
  .map(([locale, dict]) => {
    const pairs = Object.entries(dict)
      .sort(([a], [b]) => a.localeCompare(b))
      .map(([k, v]) => `    "${k}": "${v.replace(/\\/g, "\\\\").replace(/"/g, '\\"')}",`)
      .join("\n")
    return `  ${locale}: {\n${pairs}\n  }`
  })
  .join(",\n")

const source = `// Generated by scripts/generate-i18n.ts from i18n/*.yaml. Do not edit manually.\n\nexport const dictionaries = {\n${entries}\n} as const\n\nexport type I18nKey = keyof typeof dictionaries.en\nexport type ResolvedLanguage = keyof typeof dictionaries\n`

mkdirSync(outDir, { recursive: true })
writeFileSync(outFile, source)
console.log(`Generated ${outFile}`)
