use super::{field_validation::*, HealthCheckConfig};

pub(super) fn validate_health_check_config(health: &HealthCheckConfig, errors: &mut Vec<String>) {
    validate_range_f64(
        "health_check.startup_interval",
        health.startup_interval,
        0.1,
        60.0,
        errors,
    );
    validate_range_f64(
        "health_check.startup_timeout",
        health.startup_timeout,
        1.0,
        1800.0,
        errors,
    );
    validate_range_f64(
        "health_check.startup_hard_timeout",
        health.startup_hard_timeout,
        1.0,
        7200.0,
        errors,
    );
    validate_range_f64(
        "health_check.liveness_interval",
        health.liveness_interval,
        1.0,
        300.0,
        errors,
    );
    validate_range_i32(
        "health_check.liveness_failure_threshold",
        health.liveness_failure_threshold,
        1,
        10,
        errors,
    );
    validate_range_f64(
        "health_check.ping_timeout_http",
        health.ping_timeout_http,
        0.1,
        600.0,
        errors,
    );
    validate_range_f64(
        "health_check.ping_timeout_sse",
        health.ping_timeout_sse,
        0.1,
        600.0,
        errors,
    );
    validate_range_f64(
        "health_check.ping_timeout_stdio",
        health.ping_timeout_stdio,
        0.1,
        1200.0,
        errors,
    );
    validate_range_i32(
        "health_check.window_size",
        health.window_size,
        1,
        1000,
        errors,
    );
    validate_range_i32(
        "health_check.window_min_calls",
        health.window_min_calls,
        1,
        1000,
        errors,
    );
    validate_range_f64(
        "health_check.error_rate_threshold",
        health.error_rate_threshold,
        0.0,
        1.0,
        errors,
    );
    validate_range_f64(
        "health_check.latency_p95_warn",
        health.latency_p95_warn,
        0.01,
        30.0,
        errors,
    );
    validate_range_f64(
        "health_check.latency_p99_critical",
        health.latency_p99_critical,
        0.01,
        60.0,
        errors,
    );
    validate_range_f64(
        "health_check.backoff_base",
        health.backoff_base,
        0.1,
        300.0,
        errors,
    );
    validate_range_f64(
        "health_check.backoff_max",
        health.backoff_max,
        1.0,
        3600.0,
        errors,
    );
    validate_range_f64(
        "health_check.backoff_jitter",
        health.backoff_jitter,
        0.0,
        1.0,
        errors,
    );
    validate_range_i32(
        "health_check.half_open_max_calls",
        health.half_open_max_calls,
        1,
        100,
        errors,
    );
    validate_range_f64(
        "health_check.half_open_success_rate_threshold",
        health.half_open_success_rate_threshold,
        0.0,
        1.0,
        errors,
    );
    validate_range_f64(
        "health_check.reconnect_hard_timeout",
        health.reconnect_hard_timeout,
        1.0,
        7200.0,
        errors,
    );
}
