use std::env;
use std::fs;
use std::io;
use std::path::{Path, PathBuf};

fn main() -> io::Result<()> {
    generate_i18n()?;
    generate_web_assets()?;
    Ok(())
}

fn generate_i18n() -> io::Result<()> {
    let manifest_dir =
        PathBuf::from(env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR is set by Cargo"));
    let i18n_dir = manifest_dir.join("../../../i18n");
    let out_dir = PathBuf::from(env::var("OUT_DIR").expect("OUT_DIR is set by Cargo"));
    let out_file = out_dir.join("i18n_generated.rs");

    println!("cargo:rerun-if-changed={}", i18n_dir.display());

    let mut locales: Vec<(String, String, Vec<(String, String)>)> = Vec::new();
    for entry in fs::read_dir(&i18n_dir)? {
        let entry = entry?;
        let path = entry.path();
        if path.extension().and_then(|e| e.to_str()) != Some("yaml") {
            continue;
        }
        let locale = path
            .file_stem()
            .expect("yaml file has a stem")
            .to_string_lossy()
            .to_string();
        let content = fs::read_to_string(&path)?;
        let pairs = parse_yaml_flat(&content);
        locales.push((locale, path.to_string_lossy().to_string(), pairs));
        println!("cargo:rerun-if-changed={}", path.display());
    }

    locales.sort_by(|a, b| a.0.cmp(&b.0));

    if locales.is_empty() {
        return Err(io::Error::new(
            io::ErrorKind::NotFound,
            "no i18n yaml files found",
        ));
    }

    write_i18n_generated(&out_file, &locales)
}

fn parse_yaml_flat(content: &str) -> Vec<(String, String)> {
    let mut pairs = Vec::new();
    for line in content.lines() {
        let trimmed = line.trim();
        if trimmed.is_empty() || trimmed.starts_with('#') {
            continue;
        }
        let Some((key, value)) = trimmed.split_once(':') else {
            continue;
        };
        let key = key.trim();
        let value = value.trim().trim_matches('"').trim_matches('\'');
        if key.is_empty() {
            continue;
        }
        pairs.push((key.to_string(), value.to_string()));
    }
    pairs.sort_by(|a, b| a.0.cmp(&b.0));
    pairs
}

fn yaml_key_to_variant(key: &str) -> String {
    let mut variant = String::new();
    let mut capitalize = true;
    for ch in key.chars() {
        if ch == '.' || ch == '_' || ch == '-' {
            capitalize = true;
            continue;
        }
        if capitalize {
            variant.push(ch.to_ascii_uppercase());
            capitalize = false;
        } else {
            variant.push(ch);
        }
    }
    variant
}

fn write_i18n_generated(
    out_file: &Path,
    locales: &[(String, String, Vec<(String, String)>)],
) -> io::Result<()> {
    let mut output = String::new();
    output.push_str("// Generated by build.rs. Do not edit manually.\n");
    output.push_str("\n");
    output.push_str("#[derive(Clone, Copy, Debug, PartialEq, Eq)]\n");
    output.push_str("pub enum Locale {\n");
    for (locale, _, _) in locales {
        output.push_str(&format!("    {},\n", locale_to_variant(locale)));
    }
    output.push_str("}\n");
    output.push_str("\n");

    output.push_str("impl Default for Locale {\n");
    output.push_str("    fn default() -> Self {\n");
    output.push_str(&format!(
        "        Self::{}\n",
        locale_to_variant(&locales[0].0)
    ));
    output.push_str("    }\n");
    output.push_str("}\n");
    output.push_str("\n");

    output.push_str("impl Locale {\n");
    output.push_str("    pub fn as_config_value(&self) -> &'static str {\n");
    output.push_str("        match self {\n");
    for (locale, _, _) in locales {
        output.push_str(&format!(
            "            Self::{} => \"{}\",\n",
            locale_to_variant(locale),
            locale
        ));
    }
    output.push_str("        }\n");
    output.push_str("    }\n");
    output.push_str("\n");
    output.push_str("    pub fn from_config_value(value: &str) -> Option<Self> {\n");
    output.push_str("        match value.trim().to_ascii_lowercase().as_str() {\n");
    for (locale, _, _) in locales {
        let aliases = locale_aliases(locale);
        let mut line = String::from("            ");
        for (i, alias) in aliases.iter().enumerate() {
            if i > 0 {
                line.push_str(" | ");
            }
            line.push_str(&format!("\"{}\"", alias));
        }
        output.push_str(&line);
        output.push_str(&format!(" => Some(Self::{}),\n", locale_to_variant(locale)));
    }
    output.push_str("            _ => None,\n");
    output.push_str("        }\n");
    output.push_str("    }\n");
    output.push_str("}\n");
    output.push_str("\n");

    output.push_str("#[derive(Clone, Copy, Debug, PartialEq, Eq)]\n");
    output.push_str("pub enum TextKey {\n");
    let all_keys = collect_keys(locales);
    for key in &all_keys {
        output.push_str(&format!("    {},\n", yaml_key_to_variant(key)));
    }
    output.push_str("}\n");
    output.push_str("\n");

    output.push_str("pub fn text(locale: Locale, key: TextKey) -> &'static str {\n");
    output.push_str("    match locale {\n");
    for (locale, _, _) in locales {
        output.push_str(&format!(
            "        Locale::{} => {}(key),\n",
            locale_to_variant(locale),
            locale_to_fn(locale)
        ));
    }
    output.push_str("    }\n");
    output.push_str("}\n");
    output.push_str("\n");

    output.push_str(
        "pub fn text_with_args(locale: Locale, key: TextKey, vars: &[(&str, &str)]) -> String {\n",
    );
    output.push_str("    let mut s = text(locale, key).to_string();\n");
    output.push_str("    for (name, value) in vars {\n");
    output.push_str("        s = s.replace(&format!(\"{{{}}}\", name), value);\n");
    output.push_str("    }\n");
    output.push_str("    s\n");
    output.push_str("}\n");
    output.push_str("\n");

    for (locale, _, pairs) in locales {
        output.push_str(&format!(
            "fn {}(key: TextKey) -> &'static str {{\n",
            locale_to_fn(locale)
        ));
        output.push_str("    match key {\n");
        for (key, value) in pairs {
            let escaped = value.replace('\\', "\\\\").replace('"', "\\\"");
            output.push_str(&format!(
                "        TextKey::{} => \"{}\",\n",
                yaml_key_to_variant(key),
                escaped
            ));
        }
        output.push_str("    }\n");
        output.push_str("}\n");
        output.push_str("\n");
    }

    output.push_str("#[cfg(test)]\n");
    output.push_str("mod tests {\n");
    output.push_str("    use super::*;\n");
    output.push_str("\n");
    output.push_str("    #[test]\n");
    output.push_str("    fn default_locale_is_english() {\n");
    output.push_str(&format!(
        "        assert_eq!(Locale::default(), Locale::{});\n",
        locale_to_variant(&locales[0].0)
    ));
    output.push_str("    }\n");
    output.push_str("\n");
    output.push_str("    #[test]\n");
    output.push_str("    fn translates_a_known_key() {\n");
    let first_key = &all_keys[0];
    let first_variant = yaml_key_to_variant(first_key);
    let first_en = locales[0]
        .2
        .iter()
        .find(|(k, _)| k == first_key)
        .map(|(_, v)| v.clone())
        .unwrap_or_default();
    output.push_str(&format!(
        "        assert_eq!(text(Locale::default(), TextKey::{}), \"{}\");\n",
        first_variant, first_en
    ));
    output.push_str("    }\n");
    output.push_str("\n");
    output.push_str("    #[test]\n");
    output.push_str("    fn parses_config_locale_values() {\n");
    output.push_str(&format!(
        "        assert_eq!(Locale::from_config_value(\"{}\"), Some(Locale::{}));\n",
        locales[0].0,
        locale_to_variant(&locales[0].0)
    ));
    output.push_str("        assert_eq!(Locale::from_config_value(\"zh\"), Some(Locale::ZhCn));\n");
    output.push_str("        assert_eq!(Locale::from_config_value(\"unknown\"), None);\n");
    output.push_str("    }\n");
    output.push_str("}\n");

    fs::write(out_file, output)
}

fn locale_to_variant(locale: &str) -> String {
    match locale {
        "en" => "EnUs".to_string(),
        "zh" => "ZhCn".to_string(),
        _ => yaml_key_to_variant(locale),
    }
}

fn locale_to_fn(locale: &str) -> String {
    match locale {
        "en" => "en_us".to_string(),
        "zh" => "zh_cn".to_string(),
        _ => locale.replace('-', "_").replace('.', "_"),
    }
}

fn locale_aliases(locale: &str) -> Vec<String> {
    match locale {
        "en" => vec!["en".to_string(), "en-us".to_string(), "en_us".to_string()],
        "zh" => vec!["zh".to_string(), "zh-cn".to_string(), "zh_cn".to_string()],
        _ => vec![locale.to_string()],
    }
}

fn collect_keys(locales: &[(String, String, Vec<(String, String)>)]) -> Vec<String> {
    let mut keys: Vec<String> = Vec::new();
    for (_, _, pairs) in locales {
        for (key, _) in pairs {
            if !keys.contains(key) {
                keys.push(key.clone());
            }
        }
    }
    keys.sort();
    keys
}

fn generate_web_assets() -> io::Result<()> {
    let out_dir = PathBuf::from(env::var("OUT_DIR").expect("OUT_DIR is set by Cargo"));
    let out_file = out_dir.join("embedded_web_assets.rs");

    let manifest_dir =
        PathBuf::from(env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR is set by Cargo"));
    let repo_web_dir = manifest_dir.join("../../../web/dist");
    let packaged_web_dir = manifest_dir.join("assets/web");
    let web_dir = if repo_web_dir.exists() {
        repo_web_dir
    } else {
        packaged_web_dir
    };

    println!("cargo:rerun-if-changed={}", web_dir.display());

    if !web_dir.exists() {
        write_empty_assets(&out_file)?;
        return Ok(());
    }

    let mut files = Vec::new();
    collect_files(&web_dir, &web_dir, &mut files)?;
    files.sort_by(|left, right| left.0.cmp(&right.0));

    for (_, absolute) in &files {
        println!("cargo:rerun-if-changed={}", absolute.display());
    }

    write_assets(&out_file, &files)
}

fn write_empty_assets(out_file: &Path) -> io::Result<()> {
    fs::write(
        out_file,
        r#"pub struct WebAsset {
    pub path: &'static str,
    pub contents: &'static [u8],
    pub mime: &'static str,
}

pub static ASSETS: &[WebAsset] = &[];
"#,
    )
}

fn write_assets(out_file: &Path, files: &[(String, PathBuf)]) -> io::Result<()> {
    let mut generated = String::from(
        r#"pub struct WebAsset {
    pub path: &'static str,
    pub contents: &'static [u8],
    pub mime: &'static str,
}

pub static ASSETS: &[WebAsset] = &[
"#,
    );

    for (relative, absolute) in files {
        let path_literal = format!("{relative:?}");
        let absolute_literal = format!("{:?}", absolute.to_string_lossy());
        let mime_literal = format!("{:?}", mime_for_path(relative));
        generated.push_str("    WebAsset {\n");
        generated.push_str(&format!("        path: {path_literal},\n"));
        generated.push_str(&format!(
            "        contents: include_bytes!({absolute_literal}),\n"
        ));
        generated.push_str(&format!("        mime: {mime_literal},\n"));
        generated.push_str("    },\n");
    }

    generated.push_str("];\n");
    fs::write(out_file, generated)
}

fn collect_files(root: &Path, dir: &Path, files: &mut Vec<(String, PathBuf)>) -> io::Result<()> {
    for entry in fs::read_dir(dir)? {
        let entry = entry?;
        let path = entry.path();
        if path.is_dir() {
            collect_files(root, &path, files)?;
            continue;
        }
        if !path.is_file() {
            continue;
        }
        let relative = path
            .strip_prefix(root)
            .expect("asset path is under root")
            .to_string_lossy()
            .replace('\\', "/");
        files.push((relative, path));
    }
    Ok(())
}

fn mime_for_path(path: &str) -> &'static str {
    match Path::new(path).extension().and_then(|ext| ext.to_str()) {
        Some("css") => "text/css; charset=utf-8",
        Some("html") => "text/html; charset=utf-8",
        Some("ico") => "image/x-icon",
        Some("js") => "text/javascript; charset=utf-8",
        Some("json") => "application/json; charset=utf-8",
        Some("png") => "image/png",
        Some("svg") => "image/svg+xml",
        Some("wasm") => "application/wasm",
        Some("woff2") => "font/woff2",
        _ => "application/octet-stream",
    }
}
